//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leo.Blog.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Account> Sys_Account { get; set; }
        public virtual DbSet<Sys_AccountInfo> Sys_AccountInfo { get; set; }
        public virtual DbSet<Sys_Authorize> Sys_Authorize { get; set; }
        public virtual DbSet<Sys_ModuleBtn> Sys_ModuleBtn { get; set; }
        public virtual DbSet<Sys_Modules> Sys_Modules { get; set; }
        public virtual DbSet<Sys_OrgInfo> Sys_OrgInfo { get; set; }
        public virtual DbSet<Sys_Roles> Sys_Roles { get; set; }
    }
}
