//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leo.Blog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_AccountInfo
    {
        public int Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public string TelePhone { get; set; }
        public string QQ { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<int> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditDT { get; set; }
    
        public virtual Sys_Account Sys_Account { get; set; }
        public virtual Sys_OrgInfo Sys_OrgInfo { get; set; }
    }
}
