//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leo.Blog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Authorize
    {
        public int Id { get; set; }
        public Nullable<int> AuthFirstId { get; set; }
        public Nullable<int> AuthSecondId { get; set; }
        public string AuthType { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    }
}
